name: AULA_GEOCHEM
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cartopy
  - pip
  - pip:
    - cf_xarray
    - cmcrameri
    - gsw
    - jupyter
    - matplotlib
    - oceans
    - openpyxl
    - palettable
    - pooch
