name: AULA_GEOCHEM
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh=1.4
  - cartopy
  - eofs
  - erddapy
  - folium
  - geopandas
  - holoviews
  - hvplot
  - iris
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - palettable
  - pandas
  - pillow
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - sympy
  - windrose
  - xarray
  - xlrd
