name: AULA_GEOCHEM
channels:
  - conda-forge
dependencies:
  - python=3
  - cartopy
  - folium
  - geopandas
  - jupyter
  - matplotlib-base
  - openpyxl
  - pooch
  - pyjanitor
  - scikit-learn
  - seaborn
  - statsmodels
