[tool.ruff]
select = [
    "F", # flakes
    "I", # import sorting
    "U", # upgrade
]
target-version = "py37"
line-length = 120

[tool.pytest.ini_options]
addopts = "--ignore=\"2023/exe-MODIS-Chlorophyll-a/00-download-MODIS-Chlorophyll-a.ipynb\""
