name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: Setup Mamba
      uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b # v2.0.5
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: >
        micromamba create --name AULA_GEOCHEM --file environment.yml --channel conda-forge
        && micromamba activate AULA_GEOCHEM

    - name: Tests
      shell: bash -l {0}
      run: |
        micromamba activate AULA_GEOCHEM
        micromamba install pytest nbval --channel conda-forge
        python -m pytest --nbval-lax -p no:python 2023
