name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Setup Micromamba Python ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
      with:
        environment-name: AULA_GEOCHEM
        init-shell: bash
        create-args: >-
          --file environment.yml pytest nbval
          --channel conda-forge

    - name: Tests
      run: |
        python -m pytest --nbval-lax -p no:python 2023
